### ISSUE TITLE
UIWebView required to render images

### ISSUE THREAD

**Issue by hiimtmac** [nyg/HTMLWithImagesToPDF#1]
Hello,

I have a few apps that use `UIWebView` to show html content which was then converted into a PDF, then emailed. Ive recently decided to convert any `UIWebView`s to `WKWebView` due to the former's deprecation. I only use base64 encoded images in my templates but I also noticed that this change from `UI..` to `WK..` does not render images in the PDF properly anymore.

I stumbled upon this repo in my google adventure for a fix and thought I'd give it a spin. However I did notice one thing: The pdf creation only properly shows images if the `UIWebView` is still present and rendering the content also (which it is in this example).

Following the steps from the [readme]:(https://github.com/nyg/HTMLWithImagesToPDF/blob/master/README.md#bug)

A direct clone with no changes yields the following (https://github.com/hiimtmac/HTMLWithImagesToPDF/tree/master):
![with-uiwebview](https://user-images.githubusercontent.com/28935783/53040103-3864dc80-3446-11e9-970a-164dd509b61a.gif)

Everything works nicely!

However, a different branch where I removed the `UIWebView` yields the following (https://github.com/hiimtmac/HTMLWithImagesToPDF/tree/removing-uiwebview):
![no-uiwebview](https://user-images.githubusercontent.com/28935783/53040134-50d4f700-3446-11e9-8793-2f6b74b42913.gif)

In this case, the lack of `UIWebView` seems to result in images no longer rendering properly. Its like the fact the images got run through the `UIWebView` allows it to be properly rendered in a pdf. So I'm scratching my head for a solution!

Do you have any other ideas how to get images to render properly with `WKWebView` html content -> PDF??? Or also let me know if I've made some colossal mistake on my end and its something im doing wrong!

**Comment by nyg** [comment]
@hiimtmac Hi!

First, sorry for the delay... It's been quite some time since I haven't open Xcode (sadly). I did try removing UIWebView and I'm having the same problem you're having... very strange.

Maybe the API has changed we're not using WKWebView properly? If I have some time, I'll try to look it up...

**Comment by hiimtmac** [comment]
@nyg it appears https://github.com/bvankuik/TestMakeAndPrintPDF has a working solution! Looks like you have to use the web view's `UIPrintFormatter` instead of `UIMarkupTextPrintFormatter`

**Comment by nyg** [comment]
@hiimtmac Thanks, I will check it out!
